### ISSUE TITLE
Q3 ROADMAP

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/llm-compressor#30]
SUMMARY:
- [x] Avoid full pass through the model for quantization modifier
- [x] Data free `oneshot`
- [x] Runtime of GPTQ with large models – how to do a 70B model?
- [x] Runtime of GPTQ with act order
- [x] Remove “naive-quantized”
- [x] Native integration of `compressed-tensors` into `AutoModelForCausalLM` (deprecate `SparseAutoModel`)
- [x] `run-compressed` in `AutoModelForCausalLM`
- [x] KV cache quantization
- [ ] Best practices documentation
- [x] Improve runtime of GPTQ with multi-gpu `sequential_update=True`
- [ ] Support AWQ + other low bit methods
- [x] Support `MoE` models end-to-end through `vllm`
- [ ] Support `XXForConditionalLM` and embedding models 
    - #73
- [ ] Support Vision Language models
    - #73
    - https://github.com/vllm-project/llm-compressor/issues/69#issuecomment-2280014391)
- [x] Documented examples of non-llama language models (gemma, phi, qwen, mixtral, deepseek, ... request others?)
- [ ] Documented sparse transfer learning with TRL
- [ ] Simplify Smoothquant for non-llama models
- [x] Improve loading time of pack-quantized models in `SparseAutoModel`
- [x] Understand why the BoS token has impact?
- [ ] Integration with PEFT
- [x] 2:4 Sparsity

**Comment by CharlesRiggins** [comment]
This paper can be helpful for "understand why the BoS token has impact".

IntactKV: Improving Large Language Model Quantization by Keeping Pivot Tokens Intact

It is found that such huge outliers usually occur at the [BOS] token and some other uninformative initial tokens (e.g., "." or ",") at par- ticular channels, regardless of the rest of the input sequence. We thus name these tokens pivot tokens given their dominating values in the activation. The attention scores will be concentrated on these pivot tokens than the rest ones, a.k.a attention sinks (Xiao et al., 2024).

**Comment by fengyang95** [comment]
May I ask when AWQ will be supported

**Comment by robertgshaw2-neuralmagic** [comment]
> May I ask when AWQ will be supported

We are actively working on this now. Ideally in a week or so
